#
# Copyright (C) 2026 Markus Pettersson (https://www.0x23.se/)
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

config settings 'settings'
	option log_stderr '1'
	option log_stdout '1'
